-- Fixed runner for the parseBP gate. Reads NDJSON lines {"kind":"bool"|"note"|"string","pattern":"..."}
-- from stdin, parses each with Tidal's parseBP as the matching Pattern type and forces four cycles of
-- events (lazy parse exceptions must not hide). Prints FAIL lines and a summary; exits non-zero on failure.
--
-- Fail-closed: a line that is not exactly such an object (bad JSON, unknown kind, missing or unknown
-- field, trailing characters, unsupported escape) counts as a failure, and an empty input is a failure
-- too — a generator that died half-way or an empty fixture glob must never pass as "ALL OK".
--
-- Case data is generated by `pnpm emit-pattern-cases` (never committed) or kept as small fixtures under
-- haskell/fixtures/. Committed, hand-written: the generator writes data, not Haskell.
import Control.Exception (SomeException, evaluate, try)
import Control.Monad (foldM, unless)
import qualified Control.Monad as M
import Data.Char (chr, digitToInt, isHexDigit, isSpace)
import Data.List (nub)
import Sound.Tidal.Context
import System.Exit (exitFailure, exitSuccess)

data Kind = KBool | KNote | KString deriving (Eq)

instance Show Kind where
  show KBool = "Bool"
  show KNote = "Note"
  show KString = "String"

-- A tiny JSON reader for exactly {"kind": <string>, "pattern": <string>} in any key order and with any
-- whitespace. Everything else is rejected with a reason (no JSON library dependency in the harness).
type P a = String -> Either String (a, String)

skipWs :: String -> String
skipWs = dropWhile isSpace

found :: String -> String
found [] = "end of line"
found (x : _) = "'" ++ [x] ++ "'"

expect :: Char -> P ()
expect c s = case skipWs s of
  (x : rest) | x == c -> Right ((), rest)
  other -> Left ("expected '" ++ [c] ++ "' but found " ++ found other)

hex4 :: String -> Maybe (Int, String)
hex4 s = case splitAt 4 s of
  (h, rest) | length h == 4 && all isHexDigit h -> Just (foldl (\acc d -> acc * 16 + digitToInt d) 0 h, rest)
  _ -> Nothing

jsonString :: P String
jsonString s = case skipWs s of
  ('"' : rest) -> go rest
  other -> Left ("expected a string but found " ++ found other)
  where
    go ('"' : rest) = Right ([], rest)
    go ('\\' : c : rest) = case c of
      '"' -> cons '"' rest
      '\\' -> cons '\\' rest
      '/' -> cons '/' rest
      'b' -> cons '\b' rest
      'f' -> cons '\f' rest
      'n' -> cons '\n' rest
      'r' -> cons '\r' rest
      't' -> cons '\t' rest
      'u' -> unicode rest
      _ -> Left ("unsupported escape \\" ++ [c])
    go (c : rest)
      | c < ' ' = Left "control character inside a string"
      | otherwise = cons c rest
    go [] = Left "unterminated string"
    cons c rest = do
      (str, rest') <- go rest
      Right (c : str, rest')
    unicode rest = case hex4 rest of
      Just (code, rest')
        | code >= 0xD800 && code <= 0xDBFF -> surrogate code rest'
        | code >= 0xDC00 && code <= 0xDFFF -> Left "lone low surrogate"
        | otherwise -> cons (chr code) rest'
      Nothing -> Left "malformed \\u escape"
    surrogate hi ('\\' : 'u' : rest) = case hex4 rest of
      Just (lo, rest')
        | lo >= 0xDC00 && lo <= 0xDFFF -> cons (chr (0x10000 + (hi - 0xD800) * 0x400 + (lo - 0xDC00))) rest'
      _ -> Left "malformed surrogate pair"
    surrogate _ _ = Left "lone high surrogate"

member :: P (String, String)
member s = do
  (k, r1) <- jsonString s
  ((), r2) <- expect ':' r1
  (v, r3) <- jsonString r2
  Right ((k, v), r3)

membersAfterFirst :: [(String, String)] -> P [(String, String)]
membersAfterFirst acc s = case skipWs s of
  (',' : rest) -> do
    (kv, r) <- member rest
    membersAfterFirst (kv : acc) r
  ('}' : rest) -> Right (reverse acc, rest)
  other -> Left ("expected ',' or '}' but found " ++ found other)

object :: P [(String, String)]
object s = do
  ((), r1) <- expect '{' s
  case skipWs r1 of
    ('}' : rest) -> Right ([], rest)
    _ -> do
      (kv, r2) <- member r1
      membersAfterFirst [kv] r2

parseLine :: String -> Either String (Kind, String)
parseLine l = do
  (kvs, rest) <- object l
  unless (all isSpace rest) (Left ("trailing characters " ++ show (take 20 (skipWs rest))))
  let keys = map fst kvs
  M.when (length keys /= length (nub keys)) (Left "duplicate key")
  let unknown = filter (`notElem` ["kind", "pattern"]) keys
  unless (null unknown) (Left ("unknown key(s) " ++ show unknown))
  k <- maybe (Left "missing \"kind\"") Right (lookup "kind" kvs)
  p <- maybe (Left "missing \"pattern\"") Right (lookup "pattern" kvs)
  kind <- case k of
    "bool" -> Right KBool
    "note" -> Right KNote
    "string" -> Right KString
    _ -> Left ("unknown kind " ++ show k)
  Right (kind, p)

force :: (Show a) => Pattern a -> IO (Either SomeException Int)
force pat = try (evaluate (length (show (queryArc pat (Arc 0 4)))))

-- ParseError is not re-exported by Sound.Tidal.Context, so pin the pattern type on the Right side instead
asBool :: Either e (Pattern Bool) -> Either e (Pattern Bool)
asBool = id

asNote :: Either e (Pattern Note) -> Either e (Pattern Note)
asNote = id

asString :: Either e (Pattern String) -> Either e (Pattern String)
asString = id

runCase :: (Show e, Show a) => Either e (Pattern a) -> IO (Either String ())
runCase (Left e) = pure (Left (show e))
runCase (Right pat) = either (Left . show) (const (Right ())) <$> force pat

check :: (Int, Int) -> (Kind, String) -> IO (Int, Int)
check (ok, bad) (kind, s) = do
  r <- case kind of
    KBool -> runCase (asBool (parseBP s))
    KNote -> runCase (asNote (parseBP s))
    KString -> runCase (asString (parseBP s))
  case r of
    Right () -> pure (ok + 1, bad)
    Left err -> do
      -- keep this prefix in sync with scripts/build-dataset.ts, which parses FAIL lines
      putStrLn ("FAIL parse (" ++ show kind ++ "): " ++ show s ++ " -- " ++ err)
      pure (ok, bad + 1)

step :: (Int, Int) -> (Int, String) -> IO (Int, Int)
step (ok, bad) (n, l) = case parseLine l of
  Left err -> do
    putStrLn ("FAIL input line " ++ show n ++ ": " ++ err ++ " -- " ++ show (take 80 l))
    pure (ok, bad + 1)
  Right c -> check (ok, bad) c

main :: IO ()
main = do
  ls <- lines <$> getContents
  let numbered = [(n, l) | (n, l) <- zip [1 :: Int ..] ls, not (all isSpace l)]
  (ok, bad) <- foldM step (0, 0) numbered
  putStrLn (show (ok + bad) ++ " patterns checked (" ++ show ok ++ " ok, " ++ show bad ++ " failed)")
  M.when (ok + bad == 0) (putStrLn "FAIL input: no cases (an empty input is a failure, not a pass)" >> exitFailure)
  if bad == 0 then putStrLn "ALL OK" >> exitSuccess else exitFailure
